package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Axel
 */
public class LoginPanel extends javax.swing.JPanel {

    DictFrame d;
    protected boolean isLogin;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(DictFrame d) {
        initComponents();
        this.d = d;
        isLogin = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        unameTxtField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        passTxtField = new javax.swing.JPasswordField();
        resetButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setLayout(null);

        jLabel2.setText("Password");
        add(jLabel2);
        jLabel2.setBounds(80, 130, 70, 14);
        add(unameTxtField);
        unameTxtField.setBounds(160, 80, 150, 30);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        add(loginButton);
        loginButton.setBounds(120, 190, 66, 23);

        jLabel1.setText("Username");
        add(jLabel1);
        jLabel1.setBounds(80, 80, 70, 14);

        passTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passTxtFieldKeyPressed(evt);
            }
        });
        add(passTxtField);
        passTxtField.setBounds(160, 130, 150, 30);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        add(resetButton);
        resetButton.setBounds(200, 190, 70, 23);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(10, 10, 55, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String username = unameTxtField.getText();
        char[] pass = passTxtField.getPassword();
        Object[] options = {"OK"};
        if (username.equals("")) {
            JOptionPane.showOptionDialog(d,"Username / Password salah! ","WARNING",JOptionPane.PLAIN_MESSAGE,JOptionPane.QUESTION_MESSAGE,
                   null,options,options[0]);
        } else {
            if (d.controller.login(username, pass)) {
                this.isLogin = true;
                d.enter(1);
            } else {
                JOptionPane.showOptionDialog(d,"Username / Password salah! ","WARNING",JOptionPane.PLAIN_MESSAGE,JOptionPane.QUESTION_MESSAGE,
                   null,options,options[0]);
            }
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    public void setterLogout(String logout) {
        this.unameTxtField.setText(logout);
        this.passTxtField.setText(logout);
    }

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        unameTxtField.setText("");
        passTxtField.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        d.enter(1);
    }//GEN-LAST:event_backButtonActionPerformed

    private void passTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTxtFieldKeyPressed
        Object[] options = {"OK"};
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String username = unameTxtField.getText();
            char[] pass = passTxtField.getPassword();
            if (username.equals("")) {
                JOptionPane.showOptionDialog(d,"Username / Password salah! ","WARNING",JOptionPane.PLAIN_MESSAGE,JOptionPane.QUESTION_MESSAGE,
                   null,options,options[0]);
            } else {
                if (d.controller.login(username, pass)) {
                    this.isLogin = true;
                    d.enter(1);
                } else {
                   JOptionPane.showOptionDialog(d,"Username / Password salah! ","WARNING",JOptionPane.PLAIN_MESSAGE,JOptionPane.QUESTION_MESSAGE,
                   null,options,options[0]);
                }
            }
        }
    }//GEN-LAST:event_passTxtFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passTxtField;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField unameTxtField;
    // End of variables declaration//GEN-END:variables
}
