package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Axel
 */
public class LoginPanel extends javax.swing.JPanel {

    DictFrame d;
    protected boolean isLogin;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(DictFrame d) {
        initComponents();
        this.d = d;
        isLogin = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        unameTxtField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        passTxtField = new javax.swing.JPasswordField();
        resetButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2);
        jLabel2.setBounds(140, 190, 70, 15);

        unameTxtField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        unameTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unameTxtFieldKeyPressed(evt);
            }
        });
        add(unameTxtField);
        unameTxtField.setBounds(220, 130, 150, 30);

        loginButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        add(loginButton);
        loginButton.setBounds(180, 250, 66, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Username");
        add(jLabel1);
        jLabel1.setBounds(140, 140, 70, 15);

        passTxtField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passTxtFieldKeyPressed(evt);
            }
        });
        add(passTxtField);
        passTxtField.setBounds(220, 180, 150, 30);

        resetButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        add(resetButton);
        resetButton.setBounds(260, 250, 70, 30);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(10, 10, 55, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String username = unameTxtField.getText();
        char[] pass = passTxtField.getPassword();
        Object[] options = {"OK"};
        if (username.equals("")) {
            JOptionPane.showOptionDialog(d, "Username / Password salah! ", "WARNING", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE,
                    null, options, options[0]);
        } else {
            if (d.controller.login(username, pass)) {
                this.isLogin = true;
                d.enter(1);
            } else {
                JOptionPane.showOptionDialog(d, "Username / Password salah! ", "WARNING", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE,
                        null, options, options[0]);
            }
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    public void setterLogout(String logout) {
        this.unameTxtField.setText(logout);
        this.passTxtField.setText(logout);
    }

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        unameTxtField.setText("");
        passTxtField.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        d.enter(1);
    }//GEN-LAST:event_backButtonActionPerformed

    private void passTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTxtFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.loginButtonActionPerformed(null);
        }
    }//GEN-LAST:event_passTxtFieldKeyPressed

    private void unameTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unameTxtFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.loginButtonActionPerformed(null);
        }
    }//GEN-LAST:event_unameTxtFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passTxtField;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField unameTxtField;
    // End of variables declaration//GEN-END:variables
}
